---
services:
  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - /root/grafana-stack/loki:/etc/loki
    ports:
      - 3100:3100
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
      - proxy 
    environment:
      VIRTUAL_HOST: "loki.monitoring.simulalab.org"
      LETSENCRYPT_HOST: "loki.monitoring.simulalab.org"
      LETSENCRYPT_EMAIL: "it@simulalab.org"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /root/grafana-stack/prometheus:/config
      - prometheus-data:/prometheus
    environment:
      VIRTUAL_HOST: "prometheus.monitoring.simulalab.org"
      LETSENCRYPT_HOST: "prometheus.monitoring.simulalab.org"
      LETSENCRYPT_EMAIL: "it@simulalab.org"
    restart: unless-stopped
    command:
      - "--config.file=/config/prometheus.yml"
    networks:
      - prometheus
      - proxy 
#  promtail:
#    image: grafana/promtail
#    container_name: promtail
#    volumes:
#      - /var/log:/var/log
#      - /root/grafana-stack/promtail:/etc/promtail
#    # ports:
#    #   - "1514:1514" # this is only needed if you are going to send syslogs
#    restart: unless-stopped
#    environment:
#      PROMTAIL_HOSTNAME: ${PROMTAIL_HOSTNAME}
#      DROPLET_HOSTNAME: ${DROPLET_HOSTNAME}
#    command: -config.file=/etc/promtail/promtail-config.yml -config.expand-env  #--log.level=debug
#    networks:
#      - loki
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - loki
      - prometheus
      - backend
    environment:
      VIRTUAL_HOST: "grafana.monitoring.simulalab.org"
      LETSENCRYPT_HOST: "grafana.monitoring.simulalab.org"
      LETSENCRYPT_EMAIL: "it@simulalab.org"

      GF_SECURITY_ADMIN_USER: "simula"
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD} 
networks:
  loki:
  prometheus:
  backend:
    external: true
    name: http-proxy_backend
volumes:
  grafana-data:
  prometheus-data:
