server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
# local machine logs
  - job_name: local 
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
        host: ${PROMTAIL_HOSTNAME} 
        droplet: ${DROPLET_HOSTNAME}
    
#  systemd journal
#  https://grafana.com/docs/loki/latest/clients/promtail/scraping/#journal-scraping-linux-only
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
        host: ${PROMTAIL_HOSTNAME}
        droplet: ${DROPLET_HOSTNAME}
    relabel_configs:
      - source_labels:
        - __journal__systemd_unit
        target_label: systemd_unit
      - source_labels:
        - __journal__hostname
        target_label: nodename
      - source_labels:
        - __journal_syslog_identifier
        target_label: syslog_identifier


  # syslog target
  #- job_name: syslog
  #  syslog:
  #    listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
  #    idle_timeout: 60s
  #    label_structured_data: yes
  #    labels:
  #      job: "syslog"
  #  relabel_configs:
  #    - source_labels: ['__syslog_message_hostname']
  #      target_label: 'host'

